#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'bev-package==0.0.0','console_scripts','bev_node'
__requires__ = 'bev-package==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('bev-package==0.0.0', 'console_scripts', 'bev_node')()
    )
